runs but import scapy causes an error
ImportError: ('error reading bytecode from /home/ayourtch/rust/ay-2-test-pyoxidize/target/debug/lib/scapy/__pycache__/__init__.cpython-310.pyc: No such file or directory (os error 2)', 'scapy')